name: CI

on:
  push:
    branches:
    - master
    - "[0-9]+.[0-9]+"
  pull_request:
    branches:
    - master
    - "[0-9]+.[0-9]+"

jobs:
  black:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip black
    - name: Running black
      run: |
        black --check --diff .

  flake8:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip flake8
    - name: Running flake8
      run: |
        flake8 --count --show-source --statistics

  isort:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip isort
    - name: Running isort
      run: |
        isort --check-only --diff --recursive

  mypy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip mypy
    - name: Running mypy
      run: |
        mypy .
